// src/components/TechnicalCodeViewer.tsx
import React, { useState } from "react";
import { FileCode, Copy, Check, Info, Server, Database, FileText } from "lucide-react";

export const TechnicalCodeViewer: React.FC = () => {
  const [activeTab, setActiveTab] = useState<"prisma" | "api" | "pdf">("prisma");
  const [copied, setCopied] = useState<boolean>(false);

  const handleCopy = (codeText: string) => {
    navigator.clipboard.writeText(codeText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const PRISMA_CODE = `// prisma/schema.prisma
// White-Label ESL Learning Diary - MVP Schema
// Highly optimized for Korean academic contexts (Hakwons) with support for 
// dynamic brand coloring, aggregate learning objective tags, visual proof images,
// and AI narrative portfolios.

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

/// Dynamic tenant profile representing each private ESL academy or hakwon
model School {
  id            String    @id @default(uuid())
  name          String    @unique
  logoUrl       String?   // UploadThing URL for the academy seal/logo
  brandColor    String    @default("#1E3A8A") // Default branding hex color
  configuration Json?     // Hakwon-specific toggles (languages, custom report structures)
  
  teachers      Teacher[]
  students      Student[]
  subjects      Subject[]
  
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
}

/// Teachers conducting classroom anchor tasks and providing portfolio inputs
model Teacher {
  id        String     @id @default(uuid())
  email     String     @unique
  name      String
  schoolId  String
  school    School     @relation(fields: [schoolId], references: [id], onDelete: Cascade)
  
  artifacts Artifact[]
  
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
}

/// Student profiles grouped by language proficiency classes
model Student {
  id             String          @id @default(uuid())
  name           String          // Korean phonetics (e.g., "김진우" or "Jin-Woo Kim")
  classId        String?         // Class tier (e.g., "Phonics Level 2A")
  schoolId       String
  school         School          @relation(fields: [schoolId], references: [id], onDelete: Cascade)
  
  artifacts      Artifact[]
  monthlyReports MonthlyReport[]
  
  createdAt      DateTime        @default(now())
  updatedAt      DateTime        @updatedAt

  @@index([schoolId])
}

/// Dynamic learning streams tailored by each academy (e.g., Phonics, Creative Writing, Speech)
model Subject {
  id                String              @id @default(uuid())
  name              String              // E.g., "Phonics", "Speech & Debate", "Syntax Studio"
  schoolId          String
  school            School              @relation(fields: [schoolId], references: [id], onDelete: Cascade)
  
  learningObjectives LearningObjective[]
  artifacts         Artifact[]
  
  createdAt         DateTime            @default(now())
  updatedAt         DateTime            @updatedAt

  @@unique([name, schoolId])
}

/// Predefined pedagogical tags to alleviate teacher writing overhead ("Curated Autonomy")
model LearningObjective {
  id        String   @id @default(uuid())
  subjectId String
  subject   Subject  @relation(fields: [subjectId], references: [id], onDelete: Cascade)
  tagText   String   // E.g., "Short Voweling", "Oral Intonation", "Adverbial Modifiers"
  
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@unique([subjectId, tagText])
}

/// Visual anchor tasks uploaded monthly to prove student mastery
model Artifact {
  id           String   @id @default(uuid())
  studentId    String
  student      Student  @relation(fields: [studentId], references: [id], onDelete: Cascade)
  teacherId    String
  teacher      Teacher  @relation(fields: [teacherId], references: [id])
  subjectId    String
  subject      Subject  @relation(fields: [subjectId], references: [id], onDelete: Cascade)
  
  imageUrl     String   // UploadThing URL displaying the milestone worksheet or speaking video snapshot
  teacherNotes String?  // Secondary bullet lists or raw notes from the grading teacher
  aiNarrative  String?  // Orchestrated narrative generated by Gemini reflecting student growth
  tags         String[] // Assigned analytical tags (mapping to Predefined LearningObjectives)
  
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt

  @@index([studentId, createdAt])
  @@index([subjectId])
}

/// Compiled Monthly reports summarizing performance for Korean parents
model MonthlyReport {
  id         String   @id @default(uuid())
  studentId  String
  student    Student  @relation(fields: [studentId], references: [id], onDelete: Cascade)
  month      String   // Format: "YYYY-MM" (e.g., "2026-06")
  pdfUrl     String?  // Storage engine destination hosting the compiled white-label PDF document
  status     String   @default("DRAFT") // DRAFT, REVIEW_PENDING, PUBLISHED
  
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt

  @@unique([studentId, month])
}`;

  const API_CODE = `// app/api/reports/generate/route.ts
// Core Next.js API Route for aggregating student artifacts and generating reports.
// Handles multi-tenant academy parameters, aggregates portfolios by subject,
// implements layout-safe "intelligent skipping", and formats the PDF payload.

import { NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";

let prisma: PrismaClient;
if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient();
} else {
  const globalRef = global as unknown as { prisma?: PrismaClient };
  if (!globalRef.prisma) {
    globalRef.prisma = new PrismaClient();
  }
  prisma = globalRef.prisma;
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { studentId, month } = body;

    if (!studentId || !month) {
      return NextResponse.json(
        { error: "Missing required fields: studentId and month are mandatory." },
        { status: 400 }
      );
    }

    const student = await prisma.student.findUnique({
      where: { id: studentId },
      include: {
        school: {
          select: {
            id: true,
            name: true,
            brandColor: true,
            logoUrl: true,
          },
        },
      },
    });

    if (!student) {
      return NextResponse.json({ error: "Student not found." }, { status: 404 });
    }

    const subjects = await prisma.subject.findMany({
      where: { schoolId: student.schoolId },
      include: {
        learningObjectives: {
          select: { tagText: true },
        },
      },
    });

    const [yearStr, monthStr] = month.split("-");
    const startDate = new Date(parseInt(yearStr), parseInt(monthStr) - 1, 1);
    const endDate = new Date(parseInt(yearStr), parseInt(monthStr), 0, 23, 59, 59);

    const activeArtifacts = await prisma.artifact.findMany({
      where: {
        studentId,
        createdAt: { gte: startDate, lte: endDate },
      },
      include: {
        subject: true,
        teacher: { select: { name: true } },
      },
    });

    // INTELLIGENT SKIPPING: Filters subjects with zero activities
    const subjectPortfolios = subjects
      .map((subject) => {
        const matchedArtifacts = activeArtifacts.filter((art) => art.subjectId === subject.id);
        return {
          subjectId: subject.id,
          subjectName: subject.name,
          learningObjectives: subject.learningObjectives.map((o) => o.tagText),
          artifacts: matchedArtifacts.map((art) => ({
            id: art.id,
            imageUrl: art.imageUrl,
            teacherNotes: art.teacherNotes || "",
            aiNarrative: art.aiNarrative || "Progressing steadily targeting key benchmarks.",
            tags: art.tags,
            gradedBy: art.teacher.name,
            createdAt: art.createdAt.toISOString(),
          })),
        };
      })
      .filter((stream) => stream.artifacts.length > 0);

    return NextResponse.json({
      meta: {
        reportGeneratedAt: new Date().toISOString(),
        targetMonth: month,
        schoolName: student.school.name,
        schoolBrandColor: student.school.brandColor,
        schoolLogoUrl: student.school.logoUrl,
      },
      student: { id: student.id, name: student.name },
      timeline: subjectPortfolios,
    });
  } catch (error: any) {
    return NextResponse.json({ error: "Internal Server Error", details: error.message }, { status: 500 });
  }
}`;

  const PDF_CODE = `// components/PdfTemplate.tsx
// White-Label Configuration Engine & PDF Compilation layout.
// Built primarily for \`@react-pdf/renderer\` to compile multi-subject artifacts,
// dynamically inject custom brand coloring, insert school seals, and format page budgets safely.

import React from "react";
import { Document, Page, Text, View, Image, StyleSheet, Font } from "@react-pdf/renderer";

Font.register({
  family: "Inter",
  src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fAZ9hNDg.ttf",
});

export const PdfTemplate = ({ brandColor, logoUrl, schoolName, studentName, classroomName, monthName, timeline }) => {
  const styles = StyleSheet.create({
    page: { fontFamily: "Inter", backgroundColor: "#FFFFFF", padding: 40, fontSize: 10, color: "#334155" },
    coverContainer: { flex: 1, justifyContent: "space-between", alignItems: "center", paddingVertical: 50, border: \`8px solid \${brandColor}\`, borderRadius: 12 },
    schoolHeader: { alignItems: "center" },
    schoolLogo: { width: 80, height: 80, objectFit: "contain", marginBottom: 10 },
    titleSection: { alignItems: "center", marginVertical: 40 },
    badge: { backgroundColor: brandColor, color: "#FFFFFF", paddingHorizontal: 12, paddingVertical: 4, borderRadius: 20, fontSize: 8, letterSpacing: 2 },
    mainTitle: { fontSize: 32, fontWeight: "bold" },
    studentCard: { width: "80%", backgroundColor: "#F8FAFC", borderLeft: \`5px solid \${brandColor}\`, padding: 15, borderRadius: 4 },
    headerBlock: { flexDirection: "row", justifyContent: "space-between", borderBottom: \`2px solid \${brandColor}\`, paddingBottom: 10, marginBottom: 20 },
    subjectHeader: { fontSize: 14, fontWeight: "bold", backgroundColor: "#F1F5F9", padding: 6, borderLeft: \`3px solid \${brandColor}\` },
    artifactGrid: { flexDirection: "row", marginBottom: 25, gap: 15 },
    artifactImage: { width: "45%", height: 160, objectFit: "cover", borderRadius: 4 },
    tagMeta: { backgroundColor: "#EEF2F6", color: "#475569", fontSize: 7, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 3 },
    narrativeText: { fontSize: 9.5, lineHeight: 1.4, marginTop: 6 },
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.coverContainer}>
          <View style={styles.schoolHeader}>
            {logoUrl && <Image src={logoUrl} style={styles.schoolLogo} />}
            <Text>{schoolName}</Text>
          </View>
          <View style={styles.titleSection}>
            <Text style={styles.badge}>Monthly Progress Report</Text>
            <Text style={styles.mainTitle}>Multi-Subject Learning Diary</Text>
          </View>
          <View style={styles.studentCard}>
            <Text>Student: {studentName}</Text>
            <Text>Class: {classroomName}</Text>
            <Text>Month: {monthName}</Text>
          </View>
        </View>
      </Page>
      
      {timeline.map((subjectPort) => (
        <Page size="A4" key={subjectPort.subjectId} style={styles.page}>
          <View style={styles.headerBlock}>
            <Text>{studentName}'s Portfolio</Text>
            <Text style={{ color: brandColor }}>{monthName} Record</Text>
          </View>
          <Text style={styles.subjectHeader}>Subject Focus: {subjectPort.subjectName}</Text>
          {subjectPort.artifacts.map((artifact) => (
            <View key={artifact.id} style={styles.artifactGrid}>
              <Image src={artifact.imageUrl} style={styles.artifactImage} />
              <View style={{ width: "55%" }}>
                <View style={{ flexDirection: "row", gap: 4 }}>
                  {artifact.tags.map(t => <Text key={t} style={styles.tagMeta}>{t}</Text>)}
                </View>
                <Text style={styles.narrativeText}>{artifact.aiNarrative}</Text>
              </View>
            </View>
          ))}
        </Page>
      ))}
    </Document>
  );
};`;

  const getCode = () => {
    if (activeTab === "prisma") return PRISMA_CODE;
    if (activeTab === "api") return API_CODE;
    return PDF_CODE;
  };

  return (
    <div className="bg-white rounded-md border border-black/5 p-6 text-[#1C1C1C] flex flex-col h-full shadow-xs" id="tech-code-explorer">
      <div className="flex items-center justify-between pb-3 border-b border-black/5 mb-4">
        <div className="flex items-center gap-2">
          <div className="p-2 bg-[#FAF9F6] rounded-full text-[#2A435D]">
            <FileCode className="w-4 h-4" />
          </div>
          <div>
            <h2 className="font-serif font-light text-stone-900 text-lg leading-tight">Production Infrastructure Blueprints</h2>
            <p className="text-[10px] text-stone-400 font-sans uppercase tracking-wider mb-0">Next.js App Router + Prisma PostgreSQL + react-pdf compilation</p>
          </div>
        </div>

        <button
          onClick={() => handleCopy(getCode())}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-850 rounded-sm text-xs font-semibold text-white cursor-pointer transition-all"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-emerald-400" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              Copy Code
            </>
          )}
        </button>
      </div>

      {/* Code tab selectors */}
      <div className="flex gap-1 mb-4 border-b border-black/5 pb-2 ml-0" id="blueprint-tab-row">
        <button
          onClick={() => { setActiveTab("prisma"); setCopied(false); }}
          className={`flex items-center gap-1.5 px-3 py-2 rounded-t-sm text-xs font-semibold select-none transition-all cursor-pointer ${
            activeTab === "prisma"
              ? "bg-[#FAF9F6] text-[#2A435D] border-b-2 border-[#2A435D]"
              : "text-stone-400 hover:text-stone-700 hover:bg-[#FAF9F6]/50"
          }`}
        >
          <Database className="w-3.5 h-3.5 text-[#2A435D]" />
          prisma/schema.prisma
        </button>

        <button
          onClick={() => { setActiveTab("api"); setCopied(false); }}
          className={`flex items-center gap-1.5 px-3 py-2 rounded-t-sm text-xs font-semibold select-none transition-all cursor-pointer ${
            activeTab === "api"
              ? "bg-[#FAF9F6] text-[#2A435D] border-b-2 border-[#2A435D]"
              : "text-stone-400 hover:text-stone-700 hover:bg-[#FAF9F6]/50"
          }`}
        >
          <Server className="w-3.5 h-3.5 text-[#2A435D]" />
          generate/route.ts (API)
        </button>

        <button
          onClick={() => { setActiveTab("pdf"); setCopied(false); }}
          className={`flex items-center gap-1.5 px-3 py-2 rounded-t-sm text-xs font-semibold select-none transition-all cursor-pointer ${
            activeTab === "pdf"
              ? "bg-[#FAF9F6] text-[#2A435D] border-b-2 border-[#2A435D]"
              : "text-stone-400 hover:text-stone-700 hover:bg-[#FAF9F6]/50"
          }`}
        >
          <FileText className="w-3.5 h-3.5 text-[#2A435D]" />
          PdfTemplate.tsx
        </button>
      </div>

      {/* Code Text viewer container */}
      <div className="grow bg-[#FAF9F6] rounded-sm p-4 border border-black/5 max-h-[380px] overflow-y-auto font-mono text-xs text-stone-800 leading-relaxed scrollbar-thin" id="code-stream-container">
        <pre className="whitespace-pre">{getCode()}</pre>
      </div>

      <div className="mt-4 p-4 bg-[#FAF9F6] border border-black/5 rounded-sm flex items-start gap-2.5 text-xs text-stone-550 leading-relaxed" id="tech-blueprint-disclaimer">
        <Info className="w-4 h-4 text-[#2A435D] shrink-0 mt-0.5" />
        <div className="font-sans">
          <span className="font-bold text-[#2A435D] uppercase tracking-wider text-[10px] block mb-0.5">White-Label Delivery Strategy</span> These database models and endpoint blueprints represent the exact SQL schemas and layout controllers compiling inside the system directories. They integrate securely in any production Next.js or PostgreSQL pipeline.
        </div>
      </div>
    </div>
  );
};
